version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=7
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOG_LEVEL=DEBUG
      - CLI_PERSON_NAME=Federico
      - CLI_PERSON_SURNAME=Ortiz
      - CLI_PERSON_DOCUMENT=79481385
      - CLI_PERSON_BIRTHDATE=2018-03-11
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
  
  server-health-check:
    container_name: server-health-check
    image: server-health-check
    entrypoint: /health-check.sh
    build: ./health
    networks:
      - testing_net
    depends_on:
      - server
  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
